---
# Zabbix server connection
zabbix_server_ip: "192.168.1.210"  # CHANGE to your Zabbix server IP

# Zabbix agent paths
zabbix_agent_conf: /etc/zabbix/zabbix_agent2.conf
zabbix_agent_confd: /etc/zabbix/zabbix_agent2.d
zabbix_scripts_dir: /etc/zabbix/scripts
