#!/usr/bin/env python3
"""
Ansible Playbook Documentation Generator
Automatically generates README.md for each playbook and syncs to GitHub
"""

import os
import yaml
import subprocess
from pathlib import Path
from datetime import datetime

PLAYBOOKS_DIR = "playbooks"
GITHUB_REPO = "https://github.com/yairk-create/Ansible.git"

def extract_playbook_info(playbook_path):
    """Extract information from an Ansible playbook"""
    with open(playbook_path, 'r') as f:
        try:
            playbook = yaml.safe_load(f)
        except yaml.YAMLError as e:
            print(f"Error parsing {playbook_path}: {e}")
            return None
    
    if not playbook or not isinstance(playbook, list):
        return None
    
    info = {
        'name': os.path.basename(playbook_path),
        'plays': []
    }
    
    for play in playbook:
        play_info = {
            'name': play.get('name', 'Unnamed Play'),
            'hosts': play.get('hosts', 'N/A'),
            'tasks': []
        }
        
        tasks = play.get('tasks', [])
        for task in tasks:
            if isinstance(task, dict) and 'name' in task:
                play_info['tasks'].append(task['name'])
        
        info['plays'].append(play_info)
    
    return info

def generate_readme(playbook_info):
    """Generate README.md content for a playbook"""
    if not playbook_info:
        return ""
    
    readme = f"""# {playbook_info['name']}

**Last Updated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Overview
This playbook contains {len(playbook_info['plays'])} play(s).

"""
    
    for idx, play in enumerate(playbook_info['plays'], 1):
        readme += f"""### Play {idx}: {play['name']}
**Target Hosts:** `{play['hosts']}`

"""
        if play['tasks']:
            readme += "**Tasks:**\n"
            for task in play['tasks']:
                readme += f"- {task}\n"
            readme += "\n"
    
    readme += """## Usage

```bash
# Unlock Vaultwarden (if using secrets)
source unlock_vault.sh

# Run the playbook
ansible-playbook -i inventory/hosts.ini playbooks/{} --check  # Dry run
ansible-playbook -i inventory/hosts.ini playbooks/{}        # Execute
```

## Security Notes
- Passwords are stored in Vaultwarden
- SSH host key checking can be disabled for first run with `ANSIBLE_HOST_KEY_CHECKING=False`
- Always test with `--check` first

---
*Auto-generated by Ansible Documentation Agent*
""".format(playbook_info['name'], playbook_info['name'])
    
    return readme

def create_main_readme():
    """Create main README.md for the repository"""
    return """# Ansible Automation Repository

This repository contains Ansible playbooks and configurations for managing infrastructure.

## Structure

```
.
├── playbooks/          # Ansible playbooks
├── inventory/          # Inventory files
│   ├── hosts.ini      # Static inventory
│   └── group_vars/    # Group variables
├── agents.md          # Best practices guide
└── setup.sh           # Environment setup script
```

## Quick Start

1. **Setup Environment:**
   ```bash
   ./setup.sh
   source venv/bin/activate
   ```

2. **Configure Vaultwarden:**
   ```bash
   source unlock_vault.sh
   ```

3. **Run Playbooks:**
   ```bash
   ansible-playbook -i inventory/hosts.ini playbooks/site.yml
   ```

## Playbooks

"""

def setup_git_and_push():
    """Initialize git, create .gitignore, LICENSE, and push to GitHub"""
    os.chdir("/home/yair/anti")
    
    # Create .gitignore
    gitignore_content = """# Python
venv/
__pycache__/
*.pyc
*.pyo
*.pyd
.Python

# Ansible
*.retry
.vault_password

# Secrets & Credentials
**/group_vars/**/vault.yml
**/host_vars/**/vault.yml
unlock_vault.sh
create_item.json
*.json
!ansible.cfg

# Bitwarden
.config/

# OS
.DS_Store
Thumbs.db

# Temporary files
*.swp
*.swo
*~
t.json
payload.json
full_template.json
item_template.json
template.json
"""
    
    with open('.gitignore', 'w') as f:
        f.write(gitignore_content)
    
    # Create LICENSE (MIT)
    license_content = """MIT License

Copyright (c) 2026 Yair K

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""
    
    with open('LICENSE', 'w') as f:
        f.write(license_content)
    
    # Generate README for each playbook
    playbooks_path = Path(PLAYBOOKS_DIR)
    main_readme = create_main_readme()
    
    for playbook_file in playbooks_path.glob("*.yml"):
        print(f"Processing {playbook_file.name}...")
        info = extract_playbook_info(playbook_file)
        if info:
            readme_content = generate_readme(info)
            readme_path = playbook_file.parent / f"{playbook_file.stem}_README.md"
            with open(readme_path, 'w') as f:
                f.write(readme_content)
            
            # Add to main README
            main_readme += f"- [{playbook_file.name}](playbooks/{playbook_file.stem}_README.md)\n"
    
    # Write main README
    with open('README.md', 'w') as f:
        f.write(main_readme)
    
    print("\n=== Git Setup ===")
    # Git operations
    subprocess.run(['git', 'init'], check=False)
    subprocess.run(['git', 'config', 'user.name', 'Ansible Agent'], check=False)
    subprocess.run(['git', 'config', 'user.email', 'ansible@agent.local'], check=False)
    subprocess.run(['git', 'add', '.'], check=False)
    subprocess.run(['git', 'commit', '-m', 'Auto-generated documentation and initial commit'], check=False)
    
    # Add remote and push
    subprocess.run(['git', 'remote', 'add', 'origin', GITHUB_REPO], check=False)
    subprocess.run(['git', 'branch', '-M', 'main'], check=False)
    
    print("\n=== Ready to Push ===")
    print(f"Run: git push -u origin main")
    print("Note: You may need to authenticate with GitHub")

if __name__ == "__main__":
    setup_git_and_push()
    print("\n✅ Documentation generated successfully!")
