[proxmox_nodes]
node ansible_host=192.168.1.243
node1 ansible_host=192.168.1.240
node2 ansible_host=192.168.1.241

[proxmox_nodes:vars]
ansible_user=root
# We now use the exact ID or unique name to ensure the lookup finds the password
# If `proxmox_root` name doesn't work, we can fallback to searching by name
ansible_password="{{ lookup('community.general.bitwarden', 'proxmox_root', field='password') | default('') }}"

[truenas]
truenas1 ansible_host=192.168.1.203
truenas2 ansible_host=192.168.1.242
