---
all:
  children:
    proxmox_nodes:
      hosts:
        pve1:
          ansible_host: 192.168.1.10  # CHANGE to your IPs
        pve2:
          ansible_host: 192.168.1.11
        pve3:
          ansible_host: 192.168.1.12
      vars:
        ansible_user: root

    truenas:
      hosts:
        truenas01:
          ansible_host: 192.168.1.20  # CHANGE to your TrueNAS IP
      vars:
        ansible_user: root
