---
- name: Setup Administrative Users and Passwords
  hosts: all
  become: yes
  vars:
    admin_password: "L0cal1t8"
    admin_user: "yair"

  tasks:
    - name: Ensure sudo is installed
      package:
        name: sudo
        state: present

    - name: Ensure 'yair' user exists
      user:
        name: "{{ admin_user }}"
        password: "{{ admin_password | password_hash('sha512') }}"
        shell: /bin/bash
        groups: sudo
        append: yes
        state: present

    - name: Set root password
      user:
        name: root
        password: "{{ admin_password | password_hash('sha512') }}"

    - name: Allow 'yair' to use sudo without password
      copy:
        content: "{{ admin_user }} ALL=(ALL) NOPASSWD: ALL"
        dest: "/etc/sudoers.d/{{ admin_user }}"
        mode: '0440'
        validate: "/usr/sbin/visudo -cf %s"
